---
name: Data-Entropy
version: 0.005
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
abstract: entropy (randomness) management
license: perl
resources:
  license: ~
requires:
  Carp: 0
  Crypt::Rijndael: 0
  Data::Float: 0.008
  Errno: 1.00
  Exporter: 0
  IO::File: 1.03
  LWP: 5.5394
  LWP::UserAgent: 0
  Params::Classify: 0
  base: 0
  constant: 0
  fields: 0
  integer: 0
  perl: 5.006
  strict: 0
  warnings: 0
build_requires:
  Crypt::Rijndael: 0
  Data::Float: 0.008
  IO::File: 1.03
  Module::Build: 0
  Test::More: 0
  constant: 0
  perl: 5.006
  strict: 0
  warnings: 0
conflicts:
  Math::BigInt: < 1.60
  Math::BigRat: < 0.04
dynamic_config: 0
provides:
  Data::Entropy:
    file: lib/Data/Entropy.pm
    version: 0.005
  Data::Entropy::Algorithms:
    file: lib/Data/Entropy/Algorithms.pm
    version: 0.005
  Data::Entropy::RawSource::CryptCounter:
    file: lib/Data/Entropy/RawSource/CryptCounter.pm
    version: 0.005
  Data::Entropy::RawSource::Local:
    file: lib/Data/Entropy/RawSource/Local.pm
    version: 0.005
  Data::Entropy::RawSource::RandomOrg:
    file: lib/Data/Entropy/RawSource/RandomOrg.pm
    version: 0.005
  Data::Entropy::RawSource::RandomnumbersInfo:
    file: lib/Data/Entropy/RawSource/RandomnumbersInfo.pm
    version: 0.005
  Data::Entropy::Source:
    file: lib/Data/Entropy/Source.pm
    version: 0.005
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: module
